---
- name: Linux (?) CentOS Virtual Machines? Need to use commands that are
    OS independent if possible
  hosts: virtual_machines
  become: true
  become_method: sudo
  vars:
    ansible_become_password: password

  tasks:
    - name: VMware Tools installed on Linux
      ansible.builtin.yum:
        name: open-vm-tools
        state: present

    - name: VMware tools service running and auto-start
      ansible.builtin.service:
        name: vmtoolsd
        state: started
        enabled: true
