---
- name: Clean up Ubuntu 20.04
  hosts: debian_family
  become: true
  become_method: ansible.builtin.sudo
  ignore_unreachable: true

  tasks:
    - name: Load variables from variables-homelab.yaml
      ansible.builtin.include_vars:
        file: variables-homelab.yaml

    - name: Clean up disabled Snap packages
      # must use shell to use piping. Command doesn't support it
      # can't add double quotes to next line, leave as is
      ansible.builtin.shell: sudo snap list --all | awk '/disabled/{print $1, $3}' | while read snapname revision; do sudo snap remove "$snapname" --revision="$revision"; done

    - name: Clean up Apt packages
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        lock_timeout: "{{ apt_lock_timeout }}"
      retries: 2
      delay: 10

    - name: Force cleanup apt packages
      ansible.builtin.command: "sudo apt -y autoremove"
      register: force_apt_cleanup
      changed_when: '"Removing " in force_apt_cleanup.stdout'

    - name: Vacuum logs
      ansible.builtin.command: journalctl --vacuum-size=1K

    - name: Clean up old APT packages
      # cannot pass "purge" or "clean" to this command, even as stand alone
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        lock_timeout: "{{ apt_lock_timeout }}"

    - name: Clean up APT cache manually
      ansible.builtin.command: sudo apt-get clean

    # any errors here mean that PIP needs to be upgraded to the latest version
    - name: Clean up Pip cache
      ansible.builtin.command: pip3 cache purge
      register: pip_cache_clean_output
      changed_when: '"Files removed: 0" not in pip_cache_clean_output.stdout'

    - name: LAST- trim the free space now
      ansible.builtin.command: fstrim --verbose --all
